# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: rastasheep/ubuntu-sshd
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo


    steps:
       	- eval $(ssh-agent -s)
    	- mkdir -p ~/.ssh

    	- ssh-add <(echo "{{ .Environment.LAB_SSH }}")

    	- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    	- ssh -tt {{ .Environment.LAB_USER }}@{{ .Environment.LAB_IP }} "cd /var/www/html/ && git pull && php artisan cache:clear"


      
